### PR TITLE
Improvements of the Readme/ Fix deprecated assertThat/ Update build tools

### PR DESCRIPTION
**Pull request by rhavran**

### CODE REVIEW

**Comment by lsuski** [comment]
Currently travis build is disabled, so before merging we need to add circle ci setup

**Comment by mpkorstanje** [comment]
> Currently travis build is disabled, so before merging we need to add circle ci setup

Travis still works. I only removed the credentials to make snapshots and releases.

**Comment by mpkorstanje** [comment]
Or it used too last time I checked.

**Comment by lsuski** [comment]
https://travis-ci.org/cucumber/cucumber-android - repository is not active, last build was 10 months ago. I've asked Aslak about it but he said that most of the builds are moved to circle ci, so probably cucumber-android should as well.

**Comment by lsuski** [comment]
I'll try to add circleci setup today

**Comment by mpkorstanje** [comment]
In the long term you should but enabling travis took all of 2 seconds.

**Comment by mpkorstanje** [comment]
Ah. Build script is broken too. :(

**Comment by lsuski** [comment]
CircleCi does not support emulator for now, configuring Firebase Test Lab is a bit redundant for me now. So I need to stick with travis

**Comment by mpkorstanje** [comment]
I thought Circle CI worked against docker images. You may be able create one that contains the emulator you want.

**Comment by lsuski** [comment]
https://circleci.com/docs/2.0/language-android/
`Note: Running the Android emulator is not supported by the type of virtualization CircleCI uses on Linux. To run emulator tests from a job, consider using an external service like Firebase Test Lab. For more details, see the Testing With Firebase Test Lab section below`

**Comment by lsuski** [comment]
@rhavran Please add setup in cukeulator with simple android junit test to check if `useAndroidJUnitRunner` works

**Comment by rhavran** [comment]
@lsuski  Sure, actually I was aimed to add the useAndroidJUnitRunner into the separate PR, but pushed it by accident into the same branch, sorry, will fix it and add the unit tests ASAP.

**Comment by lsuski** [comment]
@rhavran I've made travis config working on master  and merge it to your fork so I don't get why you push all those changes?

**Comment by rhavran** [comment]
> @rhavran I've made travis config working on master and merge it to your fork so I don't get why you push all those changes?

Hi, @lsuski , the first time after your commit it was OK, but when I did my commit it was failing consistently, so I had to fix it. there was an issue with booting and waiting for the emulator to start.

**Comment by rhavran** [comment]
Hi @lsuski, could you please check this PR?

**Comment by lsuski** [comment]
Hi, I was very busy last 2 weeks and didn't have much time

**Comment by rhavran** [comment]
Hi @lsuski, any chances you will check, or should I just merge my changes without a review?

**Comment by lsuski** [comment]
Hi, I forgot about it because it doesn't have code changes, I've focused on your second PR.

**Pull request merged**
